version: '3.8'

services:
  db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.production
    image: ilshatziangirov1999/devops-for-programmers-project-74
    command: ["make", "test"]
