version: '3.8'

services:
  app:
    volumes:
      - ./app:/app
    command: make dev
  caddy:
    image: caddy:2.6.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
