version: '3.8'

services:
  caddy:
    image: caddy:latest
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
