version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    command: make dev
