version: '3.8'

services:
  db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=${DATABASE_NAME:-postgres}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-password}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
    build:
      context: .
      dockerfile: Dockerfile.production
    image: ilshatziangirov1999/devops-for-programmers-project-74:latest
    command: ["make", "test"]
