jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Remove existing container
        run: |
          docker rm -f <имя_контейнера> || true

      - name: Build and run tests
        run: |
          make ci

      - name: Build production image
        run: |
          docker build -f Dockerfile.production -t ilshatziangirov1999/devops-for-programmers-project-74:latest .

      - name: Push to Docker Hub
        run: |
          docker push ilshatziangirov1999/devops-for-programmers-project-74:latest
