name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
        options: >-
          --health-cmd="pg_isready -U ${{ secrets.DATABASE_USERNAME }}"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Check environment variables
        run: |
          echo "Database Username: ${{ secrets.DATABASE_USERNAME }}"
          echo "Database Password: ${{ secrets.DATABASE_PASSWORD }}"
          echo "Database Name: ${{ secrets.DATABASE_NAME }}"

      - name: Run tests
        run: docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from app

      - name: Build and push Docker image
        if: success()
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ilshatziangirov1999/devops-for-programmers-project-74:latest
