name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check current directory
      run: pwd

    - name: Install Docker Buildx
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-buildx

    - name: Run tests
      run: |
        make ci

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.production
        push: true
        tags: ilshatziangirov1999/devops-for-programmers-project-74:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
