name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: $DATABASE_USERNAME
          POSTGRES_PASSWORD: $DATABASE_PASSWORD
          POSTGRES_DB: $DATABASE_NAME
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U $DATABASE_USERNAME"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and run tests
      run: |
        docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from app

    - name: Build Docker image
      run: docker build -t ilshatziangirov1999/devops-for-programmers-project-74:latest -f Dockerfile.production .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD

    - name: Push Docker image
      run: docker push ilshatziangirov1999/devops-for-programmers-project-74:latest
